apiVersion: v1
kind: Service
metadata:
  name: modernization-app
  namespace: modernization
spec:
  selector:
    app: modernization-app
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
